Repository Dessia-tech/dessia_common, pull requests merged in 2022-11, with the labels that each got.

#403 fix(plot_dataset): change DataSet to Dataset
  dessia_common/templates/vis.min.js
Labels: Status: Ready for merge

#415 fix(to_step): remove line duplicate
  dessia_common/core.py
Labels: Status: Ready for merge

#419 Fix to_script
  CHANGELOG.md
  code_pylint.py
  dessia_common/workflow/blocks.py
  dessia_common/workflow/core.py
  tests/workflow/to_script.py
Labels: Status: Ready for merge

#417 feat(sampling): make sampling methods public and write docstrings for…
  dessia_common/datatools/sampling.py
  tests/sampling.py
  tests/workflow/workflow_sampling.py
Labels: Status: Ready for review

#410 Dev export html
  dessia_common/core.py
Labels: Status: Ready for merge

#425 ci: automated master -> testing testing -> dev
  .drone.yml
Labels: Status: Ready for merge

#420 Pydocstyle
  .drone.yml
  .pydocstylerc
  code_pydocstyle.py
  code_quality.sh
Labels: Status: Ready for merge

#398 Feat/markdowns2
  dessia_common/core.py
  dessia_common/datatools/dataset.py
  dessia_common/exports.py
  dessia_common/forms.py
  dessia_common/templates.py
  tests/ci_tests.py
  tests/markdowns.py
  tests/moving_object.py
Labels: Status: Ready for review

#405 Fix/optimization test
  tests/optimization.py
Labels: Status: Ready for review

#418 Fix/pareto
  CHANGELOG.md
  dessia_common/datatools/cluster.py
  dessia_common/datatools/dataset.py
  dessia_common/datatools/tutorials/datatools.ipynb
  dessia_common/utils/types.py
  tests/dataset.py
  tests/dataset_pareto.py
  tests/workflow/workflow_pareto.py
Labels: Status: Ready for merge

#429 Fix some Diff Dict issues
  CHANGELOG.md
  dessia_common/utils/diff.py
  tests/ci_tests.py
  tests/utils/diff.py
Labels: Status: Ready for review

#426 add kwargs/fix_plot_bug
  code_pylint.py
  dessia_common/core.py
  dessia_common/forms.py
  dessia_common/vectored_objects.py
  dessia_common/workflow/core.py
Labels: Priority: Medium

#431 Revert "Merge pull request #430 from Dessia-tech/fix/dev"
  CHANGELOG.md
  dessia_common/utils/diff.py
  tests/ci_tests.py
  tests/utils/diff.py
Labels: Status: Ready for merge

#412 feat: checks
  .drone.yml
  .pylintrc
  code_pylint.py
  dessia_common/base.py
  dessia_common/checks.py
  dessia_common/core.py
  dessia_common/datatools/dataset.py
  dessia_common/exports.py
  dessia_common/workflow/blocks.py
  dessia_common/workflow/core.py
  tests/checks.py
  tests/ci_tests.py
  tests/clustering.py
  tests/dataset.py
  tests/dataset_pareto.py
  tests/markdowns.py
  tests/models_test.py
  tests/optimization.py
  tests/workflow/power_simulation.py
Labels: Status: Ready for merge
