Repository Dessia-tech/dessia_common, pull requests merged in 2022-12, with the labels that each got.

#437 perf: deserialization enhancements
  CHANGELOG.md
  dessia_common/utils/serialization.py
Labels: Status: Ready for merge

#449 (1) Fix/doc dataset
  code_pydocstyle.py
  dessia_common/breakdown.py
  dessia_common/core.py
  dessia_common/datatools/cluster.py
  dessia_common/datatools/dataset.py
  dessia_common/datatools/metrics.py
  dessia_common/datatools/sampling.py
  dessia_common/exports.py
  dessia_common/forms.py
  dessia_common/tests.py
  dessia_common/utils/types.py
  dessia_common/vectored_objects.py
  dessia_common/workflow/core.py
  doc/source/datatools.rst
Labels: Type: Documentation, Status: Duplicate, Priority: Critical, Status: Ready for review

#450 (2) Fix/doc dataset #449 + Docstring parsing #336
  code_pydocstyle.py
  code_pylint.py
  dessia_common/breakdown.py
  dessia_common/core.py
  dessia_common/datatools/dataset.py
  dessia_common/exports.py
  dessia_common/forms.py
  dessia_common/utils/copy.py
  dessia_common/utils/docstrings.py
  dessia_common/utils/types.py
  dessia_common/vectored_objects.py
  dessia_common/workflow/core.py
Labels: Type: Documentation, Priority: Critical, Status: Ready for review

#447 (3) fix(markdown_writer): change value for none values as -
  dessia_common/exports.py
Labels: Status: Ready for merge

#436 Generate Empty Workflow
  dessia_common/workflow/core.py
Labels: Status: Ready for review

#434 chore(vectored_objects): remove
  code_pydocstyle.py
  code_pylint.py
  dessia_common/forms.py
  dessia_common/models/__init__.py
  dessia_common/models/cars.py
  dessia_common/vectored_objects.py
  scripts/workflow_concatenate.py
  tests/vectored_objects.py
Labels: Status: Ready for review

#443 ci: mount pip cache
  .drone.yml
Labels: Status: Ready for merge

#451 Fix/workflow pipe order
  CHANGELOG.md
  code_pydocstyle.py
  dessia_common/workflow/blocks.py
  dessia_common/workflow/core.py
  tests/ci_tests.py
  tests/workflow/forms_simulation.py
  tests/workflow/pipes.py
  tests/workflow/workflow_with_models.py
Labels: Priority: Critical, Status: Ready for review

#463 PATCH : Add extension to xlsx if missing
  dessia_common/core.py
Labels: Status: Ready for review
