Repository Dessia-tech/dessia_common, pull requests merged in 2023-01, with the labels that each got.

#441 (2) chore(cluster): 100 percents coverage on cluster
  CHANGELOG.md
  code_pydocstyle.py
  dessia_common/base.py
  dessia_common/breakdown.py
  dessia_common/checks.py
  dessia_common/core.py
  dessia_common/datatools/cluster.py
  dessia_common/datatools/metrics.py
  dessia_common/datatools/sampling.py
  dessia_common/displays.py
  dessia_common/errors.py
  dessia_common/exports.py
  dessia_common/files.py
  dessia_common/forms.py
  dessia_common/generation.py
  dessia_common/graph.py
  dessia_common/models/cars.py
  dessia_common/models/power_test.py
  dessia_common/models/rand_data.py
  dessia_common/models/workflows/forms_workflow.py
  dessia_common/models/workflows/power_simulation.py
  dessia_common/models/workflows/wokflow_exports.py
  dessia_common/models/workflows/workflow_from_file_input.py
  dessia_common/optimization.py
  dessia_common/templates.py
  dessia_common/tests.py
  dessia_common/typings.py
  dessia_common/utils/algebra.py
  dessia_common/utils/copy.py
  dessia_common/utils/diff.py
  dessia_common/utils/docstrings.py
  dessia_common/utils/helpers.py
  dessia_common/utils/interpolation.py
  dessia_common/utils/jsonschema.py
  dessia_common/utils/serialization.py
  dessia_common/utils/types.py
  dessia_common/warnings.py
  dessia_common/workflow/blocks.py
  dessia_common/workflow/core.py
  dessia_common/workflow/utils.py
  tests/clustering.py
  tests/optimization.py
Labels: Priority: Low, Status: Ready for review

#478 fix(block_is_valid): hot fix return always true
  CHANGELOG.md
  dessia_common/optimization.py
  dessia_common/workflow/core.py
Labels: Type: Bug, Priority: High, Status: Ready for review

#484 daily code_pydocstyle.py
  CHANGELOG.md
  code_pydocstyle.py
Labels: Status: To be discussed

#486 Pydocstyle : Finish him.
  CHANGELOG.md
  code_pydocstyle.py
  dessia_common/checks.py
  dessia_common/core.py
  dessia_common/errors.py
  dessia_common/generation.py
  dessia_common/serialization.py
  dessia_common/typings.py
  dessia_common/utils/diff.py
  dessia_common/utils/serialization.py
  dessia_common/warnings.py
  dessia_common/workflow/blocks.py
  dessia_common/workflow/core.py
Labels: Status: Ready for review

#487 Change recursion limit
  dessia_common/utils/types.py
Labels: Priority: Critical

#497 (A) Merge master back to testing
  CHANGELOG.md
  dessia_common/utils/types.py
  dessia_common/workflow/blocks.py
  dessia_common/workflow/core.py
  tests/workflow/to_script.py
  tests/workflow/workflow_method_dict.py
Labels: Priority: High, Status: Ready for review

#455 Reference path
  .drone.yml
  CHANGELOG.md
  code_pylint.py
  dessia_common/core.py
  dessia_common/datatools/cluster.py
  dessia_common/datatools/dataset.py
  dessia_common/displays.py
  dessia_common/exports.py
  dessia_common/forms.py
  dessia_common/models/workflows/forms_workflow.py
  dessia_common/serialization.py
  dessia_common/utils/helpers.py
  dessia_common/utils/serialization.py
  dessia_common/utils/types.py
  dessia_common/workflow/blocks.py
  dessia_common/workflow/core.py
  tests/jsonpointers.py
  tests/moving_object.py
  tests/unit_tests.py
Labels: Status: Ready for review

#479 feat: ci_tutorials.py added
  .drone.yml
  CHANGELOG.md
  coverage.py
  tutorials/ci_tutorials.py
Labels: Status: Ready for merge

#504 DOC: Last requirements from pydocstyle
  CHANGELOG.md
  code_pydocstyle.py
  dessia_common/__init__.py
  dessia_common/abstract.py
  dessia_common/breakdown.py
  dessia_common/checks.py
  dessia_common/core.py
  dessia_common/datatools/__init__.py
  dessia_common/datatools/cluster.py
  dessia_common/datatools/dataset.py
  dessia_common/datatools/metrics.py
  dessia_common/datatools/sampling.py
  dessia_common/displays.py
  dessia_common/errors.py
  dessia_common/exports.py
  dessia_common/files.py
  dessia_common/forms.py
  dessia_common/generation.py
  dessia_common/graph.py
  dessia_common/optimization.py
  dessia_common/serialization.py
  dessia_common/templates.py
  dessia_common/tests.py
  dessia_common/typings.py
  dessia_common/utils/algebra.py
  dessia_common/utils/copy.py
  dessia_common/utils/diff.py
  dessia_common/utils/docstrings.py
  dessia_common/utils/helpers.py
  dessia_common/utils/interpolation.py
  dessia_common/utils/jsonschema.py
  dessia_common/utils/serialization.py
  dessia_common/utils/types.py
  dessia_common/warnings.py
  dessia_common/workflow/__init__.py
  dessia_common/workflow/blocks.py
  dessia_common/workflow/core.py
  dessia_common/workflow/utils.py
Labels: Priority: Critical, Status: Ready for review

#506 (1) finish with docstyle rules
  CHANGELOG.md
  dessia_common/datatools/cluster.py
  dessia_common/datatools/dataset.py
  dessia_common/models/cars.py
  dessia_common/models/power_test.py
  dessia_common/models/rand_data.py
  dessia_common/models/workflows/forms_workflow.py
  dessia_common/models/workflows/power_simulation.py
  dessia_common/models/workflows/wokflow_exports.py
  dessia_common/models/workflows/workflow_from_file_input.py
  dessia_common/optimization.py
  dessia_common/serialization.py
  dessia_common/tests.py
  dessia_common/utils/docstrings.py
  dessia_common/utils/serialization.py
  dessia_common/workflow/blocks.py
Labels: Priority: High, Status: Ready for review, Status: Ready for merge

#483 (2) fix(refpath_dataset): implements reference path for dataset and clust…
  CHANGELOG.md
  dessia_common/datatools/cluster.py
  dessia_common/datatools/dataset.py
Labels: Priority: High, Status: Commented

#502 Perf/tests
  CHANGELOG.md
  dessia_common/core.py
  dessia_common/serialization.py
  dessia_common/utils/copy.py
  dessia_common/utils/diff.py
  dessia_common/utils/types.py
  tests/hashes.py
  tests/workflow/forms_simulation.py
Labels: Priority: High, Status: Ready for review
