Repository Dessia-tech/dessia_common, pull requests merged in 2023-02, with the labels that each got.

#513 Chore/testing to dev
  CHANGELOG.md
  dessia_common/core.py
  dessia_common/serialization.py
  dessia_common/utils/copy.py
  dessia_common/utils/diff.py
  dessia_common/utils/jsonschema.py
  dessia_common/utils/types.py
  setup.py
  tests/ci_tests.py
  tests/hashes.py
  tests/moving_object.py
  tests/unit_tests.py
  tests/workflow/forms_simulation.py
Labels: Priority: High

#514 Fix/eq attributes
  CHANGELOG.md
  dessia_common/utils/diff.py
  tests/utils/diff.py
Labels: Status: Ready for review

#515 fix: commit hash for pre-release
  .drone.yml
  .pyenchant_dessia.dict
  .pylintrc
  CHANGELOG.md
  code_pylint.py
  code_quality.sh
  dessia_common/abstract.py
  dessia_common/datatools/dataset.py
  dessia_common/datatools/sampling.py
  dessia_common/forms.py
  dessia_common/generation.py
  dessia_common/serialization.py
  dessia_common/utils/diff.py
  dessia_common/utils/types.py
  dessia_common/workflow/blocks.py
  dessia_common/workflow/core.py
  setup.py
  tests/moving_object.py
Labels: Status: Solve CI to merge

#510 refactor(workflow): perf for workflow run values
  .pyenchant_dessia.dict
  CHANGELOG.md
  dessia_common/core.py
  dessia_common/utils/types.py
  dessia_common/workflow/core.py
  tests/ci_tests.py
  tests/workflow/file_inputs.py
  tests/workflow/workflow_inputs.py
Labels: Status: Ready for review

#509 Remove dessia object kwargs
  CHANGELOG.md
  dessia_common/core.py
Labels: Status: Solve CI to merge

#440 Schemas
  CHANGELOG.md
  code_pydocstyle.py
  code_pylint.py
  coverage.py
  dessia_common/checks.py
  dessia_common/core.py
  dessia_common/measures.py
  dessia_common/models/workflows/workflow_displays.py
  dessia_common/schemas/__init__.py
  dessia_common/schemas/core.py
  dessia_common/schemas/interfaces.py
  dessia_common/serialization.py
  dessia_common/utils/copy.py
  dessia_common/utils/diff.py
  dessia_common/utils/docstrings.py
  dessia_common/utils/helpers.py
  dessia_common/utils/jsonschema.py
  dessia_common/utils/types.py
  dessia_common/workflow/blocks.py
  dessia_common/workflow/core.py
  setup.py
  tests/ci_tests.py
  tests/jsonschema.py
  tests/schemas/annotation_deserialization.py
  tests/schemas/classes.py
  tests/schemas/default_values.py
  tests/schemas/methods.py
  tests/schemas/workflows.py
  tests/unit_tests.py
  tests/utils/test_types.py
  tests/utils/types.py
  tests/workflow/power_simulation.py
  tests/workflow/workflow_sampling.py
Labels: Status: Solve CI to merge

#522 fix(str_dataset): print dataset with values that are not attributes
  CHANGELOG.md
  dessia_common/datatools/cluster.py
  dessia_common/datatools/dataset.py
  tests/dataset.py
Labels: Type: Bug, Priority: Medium, Status: Solve CI to merge

#525 Chore/master to testing
  CHANGELOG.md
  code_pylint.py
  dessia_common/core.py
  dessia_common/datatools/dataset.py
  dessia_common/workflow/core.py
  tests/moving_object.py
Labels: Status: Ready for review

#535 Fix/schemas
  .pyenchant_dessia.dict
  CHANGELOG.md
  code_pylint.py
  dessia_common/breakdown.py
  dessia_common/core.py
  dessia_common/datatools/cluster.py
  dessia_common/datatools/metrics.py
  dessia_common/datatools/sampling.py
  dessia_common/displays.py
  dessia_common/forms.py
  dessia_common/generation.py
  dessia_common/models/workflows/forms_workflow.py
  dessia_common/optimization.py
  dessia_common/schemas/core.py
  dessia_common/serialization.py
  dessia_common/utils/diff.py
  dessia_common/utils/helpers.py
  dessia_common/utils/jsonschema.py
  dessia_common/utils/serialization.py
  dessia_common/utils/types.py
  dessia_common/workflow/core.py
  test_unittests/test_schemas/__init__.py
  test_unittests/test_schemas/test_annotation_serialization.py
  test_unittests/test_schemas/test_classes.py
  test_unittests/test_schemas/test_default_values.py
  test_unittests/test_schemas/test_methods.py
  test_unittests/test_schemas/test_workflows.py
  test_unittests/test_workflow/__init__.py
  test_unittests/test_workflow/test_displays.py
  test_unittests/test_workflow/test_method_dict.py
  test_unittests/test_workflow/test_to_script.py
  test_unittests/test_workflow/test_various.py
  tests/ci_tests.py
  tests/schemas/annotation_deserialization.py
  tests/schemas/methods.py
  tests/utils/test_types.py
Labels: Status: Ready for review

#543 1 - Fix Spelling
  .pyenchant_dessia.dict
  CHANGELOG.md
  dessia_common/core.py
  dessia_common/datatools/cluster.py
  dessia_common/datatools/dataset.py
  dessia_common/forms.py
  dessia_common/generation.py
Labels: Priority: High

#546 2 - Refactor Check Platform
  CHANGELOG.md
  code_pylint.py
  dessia_common/abstract.py
  dessia_common/checks.py
  dessia_common/core.py
  dessia_common/forms.py
  dessia_common/schemas/core.py
  dessia_common/utils/jsonschema.py
  dessia_common/utils/types.py
  tests/test_schemas/test_methods.py
Labels: Status: Ready for review

#541 1 - Schemas low code improvements
  CHANGELOG.md
  code_pylint.py
  dessia_common/checks.py
  dessia_common/forms.py
  dessia_common/schemas/core.py
  dessia_common/utils/jsonschema.py
  dessia_common/utils/types.py
  tests/test_schemas/test_methods.py
Labels: Status: Ready for review
