Repository Dessia-tech/dessia_common, pull requests merged in 2023-04, with the labels that each got.

#561 fix(dataset_attr): allow deep attributes for matrix generation
  CHANGELOG.md
  dessia_common/core.py
  scripts/dataset.py
Labels: Type: Bug, Priority: Medium, Status: Ready for merge

#556 Merge branch dev_zip into dev (1)
  CHANGELOG.md
  dessia_common/core.py
  dessia_common/files.py
  dessia_common/workflow/blocks.py
Labels: Type: Feature, Status: Done

#567 Feat/attribute type
  CHANGELOG.md
  code_pylint.py
  dessia_common/files.py
  dessia_common/models/workflows/forms_workflow.py
  dessia_common/models/workflows/wokflow_exports.py
  dessia_common/schemas/core.py
  dessia_common/typings.py
  dessia_common/utils/jsonschema.py
  dessia_common/workflow/blocks.py
  dessia_common/workflow/core.py
  tests/test_schemas/test_classes.py
  tests/test_workflow/test_method_attribute.py
  tests/test_workflow/test_method_dict.py
  tests/test_workflow/test_to_script.py
Labels: Status: Commented

#575 feat/add from_markdown class method
  dessia_common/core.py
  dessia_common/document_generator.py
  scripts/docx_writer.py
Labels: Status: In progress

#570 Merge dev_docx_update into dev (2)
  CHANGELOG.md
  code_pylint.py
  dessia_common/core.py
  dessia_common/document_generator.py
  dessia_common/exports.py
  dessia_common/optimization.py
  dessia_common/schemas/core.py
  dessia_common/utils/diff.py
  dessia_common/workflow/blocks.py
  scripts/ci_scripts.py
  scripts/docx_writer.py
  scripts/markdown_to_docx.py
Labels: Status: Done, Status: Ready for review

#577 feat/rename load DessiaObject methods
  .pyenchant_dessia.dict
  CHANGELOG.md
  dessia_common/core.py
  dessia_common/serialization.py
  dessia_common/typings.py
  dessia_common/workflow/blocks.py
  dessia_common/workflow/core.py
  scripts/docx_writer.py
  scripts/models_test.py
Labels: Status: Ready for review
