Repository Dessia-tech/dessia_common, pull requests merged in 2023-03, with the labels that each got.

#537 fix: call hash instead of data hash
  CHANGELOG.md
  dessia_common/core.py
Labels: Status: Solve CI to merge

#544 perf: replace $ref with dc__ref during serialization
  .pyenchant_dessia.dict
  CHANGELOG.md
  dessia_common/__init__.py
  dessia_common/breakdown.py
  dessia_common/core.py
  dessia_common/datatools/cluster.py
  dessia_common/exports.py
  dessia_common/forms.py
  dessia_common/graph.py
  dessia_common/serialization.py
  dessia_common/tests.py
  dessia_common/workflow/core.py
  doc/source/customizing.rst
  scripts/unit_tests.py
  scripts/workflow/power_simulation.py
  tests/data-structures/2.py
  tests/test_schemas/test_methods.py
Labels: Status: Ready for review, Status: Commented

#529 feat(displays): add load by default setting
  CHANGELOG.md
  code_pylint.py
  dessia_common/core.py
  dessia_common/displays.py
  dessia_common/workflow/blocks.py
  dessia_common/workflow/core.py
Labels: Status: Ready for review

#545 Block config
  .pyenchant_dessia.dict
  CHANGELOG.md
  code_pylint.py
  dessia_common/core.py
  dessia_common/datatools/dataset.py
  dessia_common/datatools/metrics.py
  dessia_common/displays.py
  dessia_common/forms.py
  dessia_common/models/workflows/wokflow_exports.py
  dessia_common/schemas/core.py
  dessia_common/serialization.py
  dessia_common/tests.py
  dessia_common/typings.py
  dessia_common/utils/copy.py
  dessia_common/utils/types.py
  dessia_common/workflow/blocks.py
  dessia_common/workflow/core.py
  tests/test_schemas/test_default_values.py
  tests/test_schemas/test_methods.py
Labels: Status: Ready for review

#565 Merge branche issues_391 into dev
  CHANGELOG.md
  dessia_common/core.py
  dessia_common/datatools/cluster.py
  dessia_common/files.py
  dessia_common/workflow/core.py
Labels: Type: Feature, Status: Ready for review

#562 add some functions to MarkdownWriter class
  CHANGELOG.md
  dessia_common/exports.py
  dessia_common/tests.py
  scripts/markdowns.py
Labels: Type: Feature, Status: Ready for merge
