Repository Dessia-tech/dessia_common, pull requests merged in 2024-03, with the labels that each got.

#571 Save workflowrun as python script
  CHANGELOG.md
  dessia_common/measures.py
  dessia_common/schemas/core.py
  dessia_common/workflow/core.py
  dessia_common/workflow/utils.py
  tests/test_workflow/test_exports.py
  tests/test_workflow/test_workflow_run_to_script.py
Labels: Status: Ready for review

#678 Fix: workflow markdown/before memory instead of after
  CHANGELOG.md
  dessia_common/workflow/core.py
Labels: Status: Ready for review

#674 Fix: PhysicalObject.to_stl
  CHANGELOG.md
  dessia_common/core.py
Labels: Type: Bug, Status: Ready for merge

#677 Fix: object_default/schema
  CHANGELOG.md
  dessia_common/schemas/core.py
  tests/test_schemas/test_computation_structures.py
Labels: Priority: High, Status: Ready for merge

#679 Fix: add block index to workflowrun zip
  CHANGELOG.md
  dessia_common/core.py
  dessia_common/workflow/core.py
Labels: Status: Ready for merge

#683 update: dataset plot
  CHANGELOG.md
  code_pylint.py
  dessia_common/datatools/dataset.py
  scripts/dataset.py
Labels: Status: Ready for merge
